all:
	(cd LuaAlchemyDemo; ant)
	(cd MiniDemo; ant)
	(cd Rapid; ant)
	(cd EzPlatformer; ant)

clean:
	(cd LuaAlchemyDemo; ant clear)
	(cd MiniDemo; ant clear)
	(cd Rapid; ant clear)
	(cd EzPlatformer; ant clear)
